require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/zipcodes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Zipcode. As you add validations to Zipcode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ZipcodesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Zipcode.create! valid_attributes
      get zipcodes_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      zipcode = Zipcode.create! valid_attributes
      get zipcode_url(zipcode), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Zipcode" do
        expect {
          post zipcodes_url,
               params: { zipcode: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Zipcode, :count).by(1)
      end

      it "renders a JSON response with the new zipcode" do
        post zipcodes_url,
             params: { zipcode: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Zipcode" do
        expect {
          post zipcodes_url,
               params: { zipcode: invalid_attributes }, as: :json
        }.to change(Zipcode, :count).by(0)
      end

      it "renders a JSON response with errors for the new zipcode" do
        post zipcodes_url,
             params: { zipcode: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested zipcode" do
        zipcode = Zipcode.create! valid_attributes
        patch zipcode_url(zipcode),
              params: { zipcode: new_attributes }, headers: valid_headers, as: :json
        zipcode.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the zipcode" do
        zipcode = Zipcode.create! valid_attributes
        patch zipcode_url(zipcode),
              params: { zipcode: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the zipcode" do
        zipcode = Zipcode.create! valid_attributes
        patch zipcode_url(zipcode),
              params: { zipcode: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested zipcode" do
      zipcode = Zipcode.create! valid_attributes
      expect {
        delete zipcode_url(zipcode), headers: valid_headers, as: :json
      }.to change(Zipcode, :count).by(-1)
    end
  end
end
